### PR TITLE
Upgrade to Amp:^1 and pThreads:^3

### PR DESCRIPTION
**Pull request by kelunik**
WIP, do not merge.

### CODE REVIEW

**Comment by staabm** [comment]
with this changes we should also bumb the major version of amphp/thread, because massive BC break.

**Comment by kelunik** [comment]
Sure, will be `0.9.0` once it's finished.

**Comment by ProPheT777** [comment]
What is the state of this PR? Do you need help?

**Comment by kelunik** [comment]
I made the tests pass and tested a few things manually. It mainly needs testing and review. It's also not compatible with PHP 5.5 anymore then, because `pthreads` 3 requires PHP 7. /cc @bwoebi

**Comment by ProPheT777** [comment]
Ok, I saw the docs on master is currently outdated against this branch (I'm reading test as docs currently)

**Comment by kelunik** [comment]
@bwoebi @trowski Should I go ahead and merge this or will we abandon `amphp/thread` in favor of `amphp/parallel` anyway?

**Comment by kelunik** [comment]
Closing in favor of `amphp/parallel`.

**Pull request closed without merging**
